
INSERT INTO users (name, age) VALUES ("blah", 28);
INSERT INTO users (name, age) VALUES ("blah", 28);
INSERT INTO users (name, age) VALUES ("blah", 28);
INSERT INTO users (name, age) VALUES ("blah", 28);
INSERT INTO users (name, age) VALUES ("blah", 28);
INSERT INTO users (name, age) VALUES ("blah", 28);
INSERT INTO users (name, age) VALUES ("blah", 28);
INSERT INTO users (name, age) VALUES ("blah", 28);
INSERT INTO users (name, age) VALUES ("blah", 28);
INSERT INTO users (name, age) VALUES ("blah", 28);
INSERT INTO users (name, age) VALUES ("blah", 28);
INSERT INTO users (name, age) VALUES ("blah", 28);
INSERT INTO users (name, age) VALUES ("blah", 28);
INSERT INTO users (name, age) VALUES ("blah", 28);
INSERT INTO users (name, age) VALUES ("blah", 28);
INSERT INTO users (name, age) VALUES ("blah", 28);
INSERT INTO users (name, age) VALUES ("blah", 28);
INSERT INTO users (name, age) VALUES ("blah", 28);
INSERT INTO users (name, age) VALUES ("blah", 28);
INSERT INTO users (name, age) VALUES ("blah", 28);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("bleh", "bleh", 1000, "05-29-1989", "05-29-2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("bleh", "bleh", 1000, "05-29-1989", "05-29-2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("bleh", "bleh", 1000, "05-29-1989", "05-29-2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("bleh", "bleh", 1000, "05-29-1989", "05-29-2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("bleh", "bleh", 1000, "05-29-1989", "05-29-2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("bleh", "bleh", 1000, "05-29-1989", "05-29-2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("bleh", "bleh", 1000, "05-29-1989", "05-29-2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("bleh", "bleh", 1000, "05-29-1989", "05-29-2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("bleh", "bleh", 1000, "05-29-1989", "05-29-2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("bleh", "bleh", 1000, "05-29-1989", "05-29-2020");

INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (201, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (202, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (203, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (250, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (6, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (7, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (6, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (6, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (77, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (77, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (7, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2);
